# Generated by Django 3.1.7 on 2021-05-12 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_subcategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, null=True)),
                ('price', models.CharField(max_length=10)),
                ('date', models.DateField(null=True)),
                ('desc', models.CharField(max_length=120, null=True)),
                ('image', models.ImageField(default='', upload_to='content/productimages')),
                ('status', models.BooleanField(default=False)),
            ],
        ),
    ]
