# Generated by Django 2.2.10 on 2021-05-10 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_category_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='subcategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('catId', models.IntegerField()),
                ('name', models.CharField(max_length=20)),
                ('image', models.ImageField(default='', upload_to='content/subimages')),
                ('status', models.BooleanField()),
            ],
        ),
    ]
