# Generated by Django 2.2.10 on 2021-05-15 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_subcategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subcatId', models.IntegerField()),
                ('name', models.CharField(max_length=20)),
                ('price', models.CharField(max_length=20)),
                ('quantity', models.CharField(max_length=20)),
                ('unit', models.CharField(max_length=20)),
                ('image', models.ImageField(default='', upload_to='content/ProductsImg')),
                ('status', models.BooleanField()),
            ],
        ),
    ]
